### ISSUE TITLE
chore: Remove the `fix_typos` workflow

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/flutter-navigation-menu-demo#7]
This workflow doesn't appear to be working ever since it was included. So might as well remove it, since it can't properly parse the `README`, so it seems.

https://github.com/dwyl/flutter-navigation-menu-demo/actions/runs/5383416065

**Comment by nelsonic** [comment]
Sad times. https://github.com/sobolevn/misspell-fixer-action/issues/9
